### PR TITLE
Handle multiple beam files for the same module in releases

### LINKED ISSUE #59: Failing ProtocolEx consolidation during releases
The [RDF.ex](https://github.com/rdf-elixir/rdf-ex) library uses ProtocolEx for its extensible datatype system. In an app which uses RDF.ex, we're getting the following error during releases:

```bash
** (MatchError) no match of right hand side value: [
  "protocolex_releases_test/_build/prod/lib/rdf/ebin/Elixir.RDF.Literal.Datatype.Registry.Registration.beam", 
  "protocolex_releases_test/_build/prod/rel/protocolex_releases_test/lib/rdf-0.9.3/ebin/Elixir.RDF.Literal.Datatype.Registry.Registration.beam"]
    (protocol_ex 0.4.3) lib/protocol_ex.ex:426: ProtocolEx.consolidate/2
    (elixir 1.11.1) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (protocol_ex 0.4.3) lib/mix/tasks/compile.protocol_ex.ex:25: Mix.Tasks.Compile.ProtocolEx.run/1
    (mix 1.11.1) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.1) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.1) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.1) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.11.1) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
```

In the line causing this error, you're looking for the beam file of a module in the build path and expect it to return exactly one path:

```bash
[path] = Path.wildcard(glob) # TODO:  Add error reporting on this...
```

However, as you can see in the error message (showing two beam files for the same module), during releases it is normal to have the beam files in the build path in multiple places so that this pattern match will fail.

On a side note, I'd like to ask another question. When I first saw this error, I remembered your comment here and thought the missing compiler in our app using RDF.ex might be the cause.

> [...] users might need to add `compilers: Mix.compilers ++ [:protocol_ex]`, to their `mix.exs` file too.

— [https://elixirforum.com/t/panpipe-an-elixir-wrapper-around-pandoc-and-its-markdown-ast/24774/4](https://elixirforum.com/t/panpipe-an-elixir-wrapper-around-pandoc-and-its-markdown-ast/24774/4)

As it turned out this was not the case. However, I'd like to get a confirmation if my assumption about this requirement is correct. Generally, the users of RDF.ex don't have to add the protocol_ex compiler, only when they have ProtocolEx-implementations of the respective ProtocolEx protocols in their app, right?

### Steps to reproduce the problem

1. `mix new protocolex_releases_test`
2. Add `{:rdf, "0.9.3"}` as a dependency
3. `mix deps.get`
4. `MIX_ENV=prod mix release`
5. Upgrade to `{:rdf, "0.9.4"}` 
6. `mix deps.get`
7. `MIX_ENV=prod mix release`

### PR DESCRIPTION
**Pull request by marcelotto**
Here's my naive shoot to fix #59 . 

First, I noticed that the files in `rel/` are much smaller, so I assumed that these are stripped down versions of the ones in `lib/` for the release without debug info etc. Although I couldn't find any definitive answer, the [beam_lib module](https://erlang.org/doc/man/beam_lib.html) IMO strongly bakes my assumption that these are produced from the former. So, if my assumption is correct it should be sufficient to take just the first element with the beam file in `lib/`. 

I've tried this version and everything seems to work fine. The protocol dispatching can be applied successfully in the release.

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Greets, sorry for the delay, I often don't have a GUI much anymore to check websites like this with (I checked this due to your email, thanks for that!)...  ^.^;

~~I need to find a good github cli sometime that can give me push notifications from it...~~

Taking the first one could work if the result is sorted first (`lib` sorts before `rel` after all) since the OS can theoretically return any order from the glob, and then take the first if multiple, this is an easy update to your PR, I'll do it now and post another message here after a quick test on that too.  :-)

But yep, otherwise a great PR!  :-)

Hold on while I make that change and test....

**Comment by OvermindDL1** [comment]
Looks good on my simple test, merging and publishing with a version bump, few minutes...

**Comment by OvermindDL1** [comment]
Published 0.4.4.  Please test locally?  :-)

**Comment by marcelotto** [comment]
I've tested it locally and everything seems to work fine. Thanks.

**Pull request merged**
